### ISSUE TITLE
module stopwords is not found

### ISSUE THREAD

**Issue by MagedSaeed** [linuxscout/tashaphyne#2]
Dear Taha

Thanks for this great work

I am facing a problem when importing ArabicLightStemmer.

I am getting an error saying "module stopwords is not found".

Any thoughts?

Many thanks in advance,

**Comment by linuxscout** [comment]
Salam,
I fixed it, can you test.
Thanks

**Comment by MagedSaeed** [comment]
Thanks for the response
I am still running into the same issue.
Am I doing something wrong?

![image](https://user-images.githubusercontent.com/18549783/70800471-680e1800-1dbd-11ea-81fe-c873eb419428.png)

Many Thanks

**Comment by rashedomar** [comment]
Same issue

**Comment by linuxscout** [comment]
Salam,
I updated the package on pypi.org
you can use pip install now for version 3.4.1
Thanks

**Comment by MagedSaeed** [comment]
It is working fine for me now
Thanks,,

**Comment by rashedomar** [comment]
solved thanks
