### ISSUE TITLE
Incorrect root?

### ISSUE THREAD

**Issue by robertmiles3** [linuxscout/tashaphyne#4]
Hey there! I stumbled across this and tried it out a little bit today, but it seems like I'm missing something. For an input of فهم I would except the same (فهم) to come back to me as the root. Instead, it is coming back to me with a root of هم as if the ف is a prefix. Am I missing something?

```
als = ArabicLightStemmer();
word = u'فهم'
stem = als.light_stem(word)
print als.get_root().encode("utf8")
```

**Comment by linuxscout** [comment]
Hi,
I general the root extraction in Arabic is approximate due to the high rate  of ambiguity.
The given stem is a case of ambiguity because it's composed from possible suffix "هم" and a prefix "ف" which give us a non sense root.

**Comment by robertmiles3** [comment]
Yes, I just wanted to make sure there wasn’t a setting I should be using for better results.
