### ISSUE TITLE
Error when run ArListem.get_root

### ISSUE THREAD

**Issue by ahalghamdi** [linuxscout/tashaphyne#5]
.Error when run ArListem.get_root function I got this error
TypeError: '>=' not supported between instances of 'str' and 'int'

For example this code
`clean = [ArListem.get_suffix(t) for t in row if not t in stopword and not t in punc]
`
Same error with other function such as get_suffix()

**Comment by linuxscout** [comment]
يرجى مراجعة  المثال المقدم
Example:
```python
>>> ArListem = ArabicLightStemmer()
>>> word = u'أفتكاتبانني'
>>> stem = ArListem.light_stem(word)
>>> print ArListem.get_suffix()
 انني
```
