### ISSUE TITLE
root extraction gives different result 

### ISSUE THREAD

**Issue by hamzam0n** [linuxscout/tashaphyne#7]
i have a weird issue using .get_root() method.. 
every time i restart the kernel of my IDE or COLAB and i rerun the code it gives different root..
if i rerun the code it gives same root, but after restarting the kernel gives different roots

**Comment by linuxscout** [comment]
Salam,
can you give me some data to show how it works
thanks

**Comment by hamzam0n** [comment]
https://drive.google.com/file/d/13gez-dAftlzRF7ZKJzkQDh8B4HU1sYp8/view?usp=sharing
I can offer you the code and the examples after doing the stemming in email if you want ..

**Comment by linuxscout** [comment]
can you send me the code to taha.zerrouki @gmail.com

**Comment by hamzam0n** [comment]
i sent it to you sir

**Comment by linuxscout** [comment]
Fix bug in choosing root
    
    This bug is due to the case where a two roots have the same frequency,
    The root is chosen by _choose_root(); by selecting some criteria, then
    select the most common, if two roots have the same max frequencies.
